# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y libusb-1.0-0-dev
      - run: sudo apt-get install -y libglib2.0-dev
      - run: sudo apt-get install -y libgstreamer1.0-0 libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
      # specify any bash command here prefixed with `run: `
      - run: go build main.go
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run: 
          command: |
            go test -v -coverprofile=coverage.txt -covermode=atomic ./...
            mv coverage.txt /tmp/artifacts 
      - codecov/upload:
          file: /tmp/artifacts/coverage.txt
