on: [push]

name: Build Activator Test
jobs:
  build_windows_activator:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: compile
        run: |
          md build
          cmake -DCMAKE_BUILD_TYPE=Debug -S "./" -B build
          cmake --build build --target windows_activator -j 12        
        working-directory: ./windows_activator